version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
    commands:
      - echo Entering install phase...
  pre_build:
    commands:
      - echo Entering pre_build phase...
  build:
    commands:
      - echo Entering build phase ...
      - type foo >/dev/null 2>&1 || { echo >&2 "I require foo but it's not installed.  Aborting."; exit 1; }
      - echo This shouldn't run
  post_build:
    commands:
      - echo Entering post_build phase ...